### ISSUE TITLE
about loss value

### ISSUE THREAD

**Issue by long123524** [jocpae/clDice#11]
Hello, I successfully added cldice to the network, but the final result is very unsatisfactory, the loss value is very strange, I want to seek some suggestions or solutions
![image](https://user-images.githubusercontent.com/73996375/127460861-056cf6db-1e02-4b56-8eb6-a181b8e558d1.png)

**Comment by jocpae** [comment]
Hi, 
it is not possible for me to comment on your problem based on the given image. 
I would need substantially more information on your task/training/and implementation. I would also kindly ask you not to raise issues and delete them every hour which are related to debugging, but rather explain, structure and formulate issues thoroughly.
