### ISSUE TITLE
adding cldice degrades the performance 

### ISSUE THREAD

**Issue by yangzhenghao** [jocpae/clDice#18]
I am using cldice to vessel segmentation task, I found when I use cldice the performance(dice, jacard, hd, asd) degrades. Besides the loss will be negative.
(Plus, I divide cldice into dice and cldice with the default setting.
 
![image](https://user-images.githubusercontent.com/25858564/149507609-17ffdeaa-6636-46d1-ad1e-89567ce0ab4b.png)
![image](https://user-images.githubusercontent.com/25858564/149507663-3bc86c3a-87f0-4c97-8302-fa8ca1a0ecb2.png)

I wonder whether I mistake some setting or the wrong use of the loss?

**Comment by jocpae** [comment]
Hi, this is an interesting problem, your curves seem to indicate initially that the loss is going down. It should however never become below zero. This is where ther error is somewhere I assume. Hard to comment without more detail on the implementation and task at hand (what kind of data? What is the radius of your foreground objects?). One thing to keep in mind, the 'alpha' (the impace of the cldice) is a tunable parameter which you can tune and experiment with for your task.
