### ISSUE TITLE
Thin vessel disappear when use soft_skeleton 

### ISSUE THREAD

**Issue by yangzhenghao** [jocpae/clDice#19]
Hello, when I use soft_skeleton, I found only large vessels left no matter how I set the iteration, please tell me what should I do? I'm a little confused about the theory.
Thanks!

**Comment by jocpae** [comment]
Hi,
this is very unusual behaviour as you can see in the figure in our github page the small vessels get extracted first. Are you sure you are looking at S_final? Can you share an example ?
