### ISSUE TITLE
Two questions:1.Can you explain the 'smooth' parameter? 2.Does your clDice only calculate the loss of the foreground and ignore the background?

### ISSUE THREAD

**Issue by ZhouYanFeng19980129** [jocpae/clDice#5]
Thank you for your research!
I have two questions. 
1.Can you explain the 'smooth' parameter? 
2.Does your clDice only calculate the loss of the foreground and ignore the background?
thank you for your reply!

**Comment by jocpae** [comment]
Hi thanks for your questions! 
1) the smooth parameter is there to prevent division by zero when there is no foreground in your image patch
2) yes we do only calculate the loss on the foreground for most of our experiments. In our [paper](https://openaccess.thecvf.com/content/CVPR2021/html/Shit_clDice_-_A_Novel_Topology-Preserving_Loss_Function_for_Tubular_Structure_CVPR_2021_paper.html) we describe why this is a fair approximation.
